Generate specialized unify based on t2
jasonhemann/minikanren-ee pull request #33
Opened 2022-07-27 17:11 UTC by jasonhemann

Does not use any of the pass flags currently, but does generate specialized unify based on size of term.

2022-07-27 17:13 UTC, jasonhemann commented
If accepted, probably best to squash and merge, because there are many intermediate states, some pretty questionable.

2022-07-30 15:04 UTC, gamburgm requested changes
Great progress! Left a few suggestions and questions

2022-07-30 15:04 UTC, gamburgm commented on private/compile/generate-equiv.rkt
> +     #`(cons #,(generate-term #'t1) #,(generate-term #'t2))]))
I'd recommend a test suite here that just generates code for single `==`, i.e. relations that look like this:

```racket
(ir-rel (SOME BINDER)
  (== [TERM1] [TERM2]))
```

And just have one test for each meaningful case that you want to specialize (maybe not the `rkt-term on left-hand-side` ones since we don't care as much about that)

2022-07-30 15:04 UTC, gamburgm commented on test/equiv-tests.rkt
> +  ;; (test-equal?
Why are these tests commented out?

2022-07-30 15:04 UTC, gamburgm commented on private/compile/generate-code.rkt
> +         (mku:fresh ()
Some of these tests will fail when merging with master, because of the changes made to codegen for `conj` and `disj`

2022-07-30 15:40 UTC, jasonhemann commented
🤘🤘

2022-08-06 01:47 UTC, jasonhemann commented on private/compile/generate-equiv.rkt
> +(define/hygienic (generate-specialized-unify-rkt-term v t2) #:expression
Let's talk about this one tomorrow; I think I get most of the rest of these.

2022-08-06 01:47 UTC, jasonhemann commented on private/compile/generate-equiv.rkt
> +     #`(cons #,(generate-term #'t1) #,(generate-term #'t2))]))
And this one also.

2022-08-06 13:51 UTC, jasonhemann commented on private/compile/generate-equiv.rkt
> +     #`(let ([w^ (mku:walk w #,S)])
Maybe it doesn't matter b/c it's just removing a function call! I'm like to want to undo this b/c it's smaller code!

2022-08-19 20:04 UTC, jasonhemann commented on private/compile/generate-code.rkt
> +         (mku:fresh ()
Surprisingly these tests did not change when I merged with master. Maybe we should look at why that is.

2022-08-20 13:47 UTC, jasonhemann commented on private/compile/generate-equiv.rkt
> +(define/hygienic (generate-specialized-unify-rkt-term v t2) #:expression
Did the exact same thing there; so this is no longer specialized.

2022-08-20 13:50 UTC, merged